version: '3.8'

networks:
  app_network:
    driver: bridge

services:
  grafana:
    image: grafana/grafana
    user: root
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./base/grafana:/var/lib/grafana
      - ./base/grafana/provisioning/:/etc/grafana/provisioning/
    container_name: grafana
    hostname: grafana
    environment:
      TZ: "Europe/Moscow"
      GF_SECURITY_ALLOW_EMBEDDING: "true"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
    networks:
      - app_network

  influxdb:
    image: influxdb
    container_name: influxdb
    env_file:
      - influx.env
    volumes:
      - ./base/influx:/var/lib/influxdb2:rw
    ports:
      - "8086:8086"
    networks:
      - app_network

  telegraf:
    image: telegraf
    container_name: telegraf
    depends_on:
      - influxdb
    volumes:
      - ./base/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    env_file:
      - influx.env
    networks:
      - app_network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "5433:5433"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_ADDRESS: 0.0.0.0
      PGADMIN_LISTEN_PORT: 5433
      PGADMIN_DEFAULT_SERVER: postgres_db
    volumes:
      - ./base/pgadmin_data:/var/lib/pgadmin
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - app_network
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:15
    container_name: postgres_db
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - app_network
    volumes:
      - ./base/postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
